kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstore-covers-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
