apiVersion: v1
kind: Secret
metadata:
  name: db-connection
type: Opaque
data:
  username: {{ .Values.postgresql.postgresqlUsername }}
  password: {{ .Values.postgresql.postgresqlPassword }}
  database: {{ .Values.postgresql.postgresqlDatabase }}
  host: {{ .Release.Name}}-postgresql
