apiVersion: v1
kind: Secret
metadata:
  name: db-connection
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  database: {{ .Values.postgresql.auth.database | b64enc }}
  host: {{ print .Release.Name "-postgresql" | b64enc }}
