apiVersion: v1
kind: Secret
metadata:
  name: restic-secret
type: Opaque
data:
  RESTIC_PASSWORD: {{ .Values.backup.RESTIC_PASSWORD | b64enc }}
  RESTIC_REPOSITORY: {{ print "swift:sb_project_" .Values.backup.RESTIC_USERNAME ":/Liip-MaaS" | b64enc }}
  OS_AUTH_URL: {{ .Values.backup.OS_AUTH_URL | b64enc }}
  OS_PROJECT_NAME: {{ print "sb_project_" .Values.backup.RESTIC_USERNAME | b64enc }}
  OS_USERNAME: {{ .Values.backup.RESTIC_USERNAME | b64enc }}
  OS_PASSWORD: {{ .Values.backup.OS_PASSWORD | b64enc }}
  OS_REGION_NAME: {{ .Values.backup.OS_REGION_NAME | b64enc }}
  OS_USER_DOMAIN_NAME: {{ .Values.backup.OS_USER_DOMAIN_NAME | b64enc }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.backup.OS_PROJECT_DOMAIN_NAME | b64enc }}
  DAILY_RETENTION: {{ .Values.backup.DAILY_RETENTION | quote | b64enc }}
  WEEKLY_RETENTION: {{ .Values.backup.WEEKLY_RETENTION | quote | b64enc }}
  MONTHLY_RETENTION: {{ .Values.backup.MONTHLY_RETENTION | quote | b64enc }}
