apiVersion: v1
kind: Secret
metadata:
  name: restic-secret
type: Opaque
data:
  RESTIC_PASSWORD: {{ .Values.backup.RESTIC_PASSWORD }}
  RESTIC_REPOSITORY: 'swift:sb_project_{{ .Values.backup.RESTIC_USERNAME }}:/Liip-MaaS'
  OS_AUTH_URL: {{ .Values.backup.OS_AUTH_URL }}
  OS_PROJECT_NAME: 'sb_project_{{ .Values.backup.RESTIC_USERNAME }}'
  OS_USERNAME: {{ .Values.backup.RESTIC_USERNAME }}
  OS_PASSWORD: {{ .Values.backup.OS_PASSWORD }}
  OS_REGION_NAME: {{ .Values.backup.OS_REGION_NAME }}
  OS_USER_DOMAIN_NAME: {{ .Values.backup.OS_USER_DOMAIN_NAME }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.backup.OS_PROJECT_DOMAIN_NAME }}
  DAILY_RETENTION: "{{ .Values.backup.DAILY_RETENTION }}"
  WEEKLY_RETENTION: "{{ .Values.backup.WEEKLY_RETENTION }}"
  MONTHLY_RETENTION: "{{ .Values.backup.MONTHLY_RETENTION }}"
