# .github/workflows/deploy.yml
name: Deploy
on: ['deployment', 'workflow_dispatch']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: Deploy helm chart
        uses: WyriHaximus/github-action-helm3@v2
        env:
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          RESTIC_PASSWORD: ${{ secrets.RESTIC_PASSWORD }}
          RESTIC_USERNAME: ${{ secrets.RESTIC_USERNAME }}
          RESTIC_OS_AUTH_URL: ${{ secrets.RESTIC_OS_AUTH_URL }}
          RESTIC_OS_PASSWORD: ${{ secrets.RESTIC_OS_PASSWORD }}
          RESTIC_OS_REGION_NAME: ${{ secrets.RESTIC_OS_REGION_NAME }}
          RESTIC_OS_USER_DOMAIN_NAME: ${{ secrets.RESTIC_OS_USER_DOMAIN_NAME }}
          RESTIC_OS_PROJECT_DOMAIN_NAME: ${{ secrets.RESTIC_OS_PROJECT_DOMAIN_NAME }}
        with:
          exec: |
            helm repo add bitnami https://charts.bitnami.com/bitnami &&
            helm dependency build infra/bookstore &&
            helm upgrade bookstore infra/bookstore --install --wait --atomic --namespace=bookstore --values=infra/bookstore/values.yaml --set postgresql.postgresqlPassword=$POSTGRESQL_PASSWORD --set backup.RESTIC_PASSWORD=$RESTIC_PASSWORD --set backup.RESTIC_USERNAME=$RESTIC_USERNAME --set backup.OS_AUTH_URL=$RESTIC_OS_AUTH_URL --set backup.OS_PASSWORD=$RESTIC_OS_PASSWORD --set backup.OS_REGION_NAME=$RESTIC_OS_REGION_NAME --set backup.OS_USER_DOMAIN_NAME=$RESTIC_OS_USER_DOMAIN_NAME --set backup.OS_PROJECT_DOMAIN_NAME=$RESTIC_OS_PROJECT_DOMAIN_NAME
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Scale down
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: scale --replicas=0 deployment/bookstore -n bookstore

      - name: Scale up
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_BASE64 }}
        with:
          args: scale --replicas=1 deployment/bookstore -n bookstore

